services:
  web-app:
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"

  server:
    build:
      context: ./backend
      target: final
    ports:
      - "4321:8080"
    environment:
      AllowedHosts: "*"
      MongoDbSettings__ConnectionString: "mongodb://root:example@mongo:27017/"
      MongoDbSettings__DatabaseName: "leitnersystem-dev"
      MongoDbSettings__CardsCollectionName: "cards"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  db-data:


